Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  noAuthWordDic:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName2: noAuthWordDic
      AttributeDefinitions:
        - AttributeName: wordGroupId
          AttributeType: S
        - AttributeName: wordId
          AttributeType: S
      KeySchema:
        - AttributeName: wordGroupId
          KeyType: HASH
        - AttributeName: wordId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
